version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
  - nuget restore Microservice.sln 
  - choco install opencover.portable
  - choco install codecov


build:
  verbosity: detailed
  project: Microservice.sln  



