version: 1.0.{build}
branches:
  except:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  verbosity: detailed
  project: ServiceModelEx.ServiceFabric\Microservice.sln
  publish_wap:true

notifications:
- provider: Email
  to:
  - rafae11@email.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
  